package adts;

/**
 * Represents the shared functionality for operations
 * on any collection.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @param <T> the type of elements in the collection
 *
 * @author Josh Archer
 * @version 1.0
 */
public interface ICollection<T> extends Iterable<T>
{
    /**
     * Adds an element to the collection.
     *
     * @param element the element to add
     */
    void add(T element);

    /**
     * Searches for and removes the first occurrence of an element
     * from the collection.
     *
     * @param element the element to search for
     * @throws java.util.NoSuchElementException if the element
     * is not found
     */
    void remove(T element);

    /**
     * Returns true if the element is located in the collection,
     * or otherwise false.
     *
     * @param element the element to search for
     * @return true if the element is found, otherwise false
     */
    boolean contains(T element);

    /**
     * Returns the number of elements in the collection.
     * @return the element count
     */
    int size();

    /**
     * Returns true if the collection is empty, or otherwise false
     * @return true if the collection is empty, or otherwise false
     */
    boolean isEmpty();

    /**
     * Removes all elements from the collection.
     */
    void clear();
}
